### PR TITLE
Make Travis happy

### PR DESCRIPTION
**Pull request by shields-fn**

### CODE REVIEW

**Comment by shields-fn** [comment]
Why can't I get travis-ci.org to build this?

**Comment by jeevb** [comment]
> Why can't I get travis-ci.org to build this?

There is another instance of it: https://github.com/freenome/pluspl.us/blob/89b00d75cf63964be51fa9ff9bf3024050b05225/Dockerfile#L22

**Comment by shields-fn** [comment]
> > Why can't I get travis-ci.org to build this?
> 
> There is another instance of it:
> 
> https://github.com/freenome/pluspl.us/blob/89b00d75cf63964be51fa9ff9bf3024050b05225/Dockerfile#L22

Well, the problem I'm having is that `.org` Travis won't even start the build, because the repo isn't "activated", and the "activate repo" button gave a completely unhelpful error.

I just hit the button again, though, and it worked. Great job, Travis.

**Comment by shields-fn** [comment]
> There is another instance of it:
> 
> https://github.com/freenome/pluspl.us/blob/89b00d75cf63964be51fa9ff9bf3024050b05225/Dockerfile#L22

Looks like this one could be `libpq` instead of `libpq-dev`.

**Pull request merged**
